### PR TITLE
Fix Toolbar style

### LINKED ISSUE #248: Use white font and white hamburger icon in action bar

### PR DESCRIPTION
**Pull request by HenriqueRocha**
Closes #248

## Before
toolbar_before

## After
toolbar_after

### CODE REVIEW

File: app/src/main/java/org/gdg/frisbee/android/adapter/ChapterAdapter.java [hunk 1]
```diff
@@ -44,21 +39,27 @@ public ChapterAdapter(Context context, int textViewResourceId) {
...
     }
 
-    public ChapterAdapter(Context context, int textViewResourceId, List<Chapter> objects) {
-        super(context, textViewResourceId, objects);
-        mInflater = LayoutInflater.from(context);
+    @Override
+    public View getView(final int position, final View convertView, final ViewGroup parent) {
+        View view = convertView;
+        if (view == null) {
+            view = mInflater.inflate(R.layout.spinner_item_actionbar, parent, false);
```
Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/adapter/ChapterAdapter.java]: The constructor does not need the "textViewResourceId" (which was a layout resource anyway)

**Comment by friedger** [comment]
Nice!
