### PR TITLE
586/Make organizer check callback cancelable

### LINKED ISSUE #586: Crash when signing out
When signing out in settings:
http://crashes.to/s/0faa6a480a5

The settings activity was opened from the events page

### PR DESCRIPTION
**Pull request by friedger**
This PR integrates the organizer check callback better into the activity life cycle.

Fixes #586

### CODE REVIEW

File: app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java [hunk 1]
```diff
@@ -205,21 +214,13 @@ public void onConnected(Bundle bundle) {
     private void updateChapterPages() {
         final boolean wasOrganizer = mViewPagerAdapter != null
             && mViewPagerAdapter.getCount() == ORGANIZER_PAGES.length;
+        if (organizerCheckCallback != null) {
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java]: It would be great to initialize this at the beginning with `wasOrganizer = false` to make sure that it is never null.

Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java]: It should be null whenever the task has finished.

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java]: You never make it null again in the code.

Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java]: Not sure how to do it from within the callback. It is set to null in onPause. (This does not prevent leaking the activity).

I prefer to think of the callback as a nullable, kind of "transient" object. I don't like to create an object to then throw it away (for the reason of clean code).

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java]: That's the problem. onPause does not make it null.

File: app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java [hunk 2]
```diff
@@ -197,32 +199,36 @@ protected void onResume() {
...
-                @Override
-                public void onErrorResponse() {
-                }
-            }
+            organizerCheckCallback
         );
     }
 
+    private boolean isOrganizerFragmentShown() {
+        return mViewPagerAdapter != null
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/chapter/MainActivity.java]: :+1: this is good.

**Comment by tasomaniac** [comment]
LGTM
