### PR TITLE
Fix 3 achievements

### LINKED ISSUE #533: New Achievement bugs
- [X] Achievement after sending a feedback does not work for me. 
- [x] When we migrate Feeling Social achievement, it worked for me but it unlocked level 3 but it skipped level 2. 
- [X] Power user is not implemented at all.

### PR DESCRIPTION
**Pull request by tasomaniac**
- KissesFromGdgXTeam
- FeelingSocial - 2 step achievements
- Power User

achievements are fixed. 

Fixes #533

### CODE REVIEW

File: app/src/main/java/org/gdg/frisbee/android/appwidget/GdgDashClockExtension.java [hunk 1]
```diff
@@ -1,64 +1,66 @@
...
+
+import java.util.ArrayList;
+
+import timber.log.Timber;
+
+public class GdgDashClockExtension extends DashClockExtension {
+
+    @Override
+    protected void onUpdateData(int i) {
+        PrefUtils.setWidgetAdded(this);
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/appwidget/GdgDashClockExtension.java]: I am not sure what caused this huge change but I only added this line.

File: app/src/main/java/org/gdg/frisbee/android/appwidget/UpcomingEventWidgetProvider.java [hunk 2]
```diff
@@ -1,177 +1,177 @@
...
+        }
+
+        private void showChild(RemoteViews views, int i) {
+            views.setDisplayedChild(R.id.viewFlipper, i);
+        }
+    }
+
+    @Override
+    public void onUpdate(Context context, final AppWidgetManager appWidgetManager, int[] appWidgetIds) {
+        PrefUtils.setWidgetAdded(context);
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/appwidget/UpcomingEventWidgetProvider.java]: Here as well. Only this line.

File: app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java [hunk 3]
```diff
@@ -103,6 +105,14 @@ public void onCreate(Bundle savedInstanceState) {
         addProperty("loggedIn", PrefUtils.isSignedIn(getActivity())); // Optionally add some properties
         addProperty("appStarts", PrefUtils.getAppStarts(getActivity()));
         buildProperties();
+
+        setRetainInstance(true);
```
Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java]: Why do you want to retain the instance?

File: app/src/main/java/org/gdg/frisbee/android/appwidget/GdgDashClockExtension.java (hunk 1 above)
Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/appwidget/GdgDashClockExtension.java]: It is the indenting. We should run reformat on the whole project.

File: app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java (hunk 3 above)
Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java]: Better reset the achievement handler on detachActivity.

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java]: I kinda had to. The problem is with the implementation of Doorbell's SDK we are using. 
They are dismissing the Dialog once the Send button is clicked and then they make the API request. In their Rest API class, they have a reference to Activity. 

So the problem is that achievement handler's method is run after `detachActivity` because of this. 

I wanted to change it completely. I wanted to make the dialog dismiss after API request finishes. Their callback only have `success` in it. We won't be notified if there is a network issue and the user will be stuck. 

I unfortunately couldn't figure out a better way because of this.

Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java]: What about leaving the dialog open until doorbell comes back with a result?

There is also the `setErrorCallback`

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/widget/FeedbackFragment.java]: I didn't know that there is error Callback method. We can do that. It would
make sense. Btw the dialog does not survive orientation change.

**Comment by friedger** [comment]
LGTM, waiting for the checks to compelete
