### PR TITLE
Fix pulse numbering bug. 

### LINKED ISSUE #451: Pulse numbering bug.
As it can be seen in the screenshots, we have a problem with the numbering of the items. 

screenshot_20150802-234650
screenshot_20150802-234709

### PR DESCRIPTION
**Pull request by tasomaniac**
The problem is because FragmentStatePagerAdapter was aggressively caching the states of its children Fragments. 
Here is the bug reported and it is still open. https://code.google.com/p/android/issues/detail?id=37990

There are couple of ways to fix it using a really really custom FragmentStatePagerAdapter without subclassing it. I don't like those solutions. It is not optimal but recreating the adapter fixes this problem. 

The problem is actually because of the positions calculation in the code. On orientation change it reset and makes another problem. I saved it on config change and now it works perfectly. 

Fixes #451

### CODE REVIEW

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java [hunk 1]
```diff
@@ -117,23 +122,16 @@ public void setPulse(final int mode, Pulse pulse) {
...
-                switch (mode) {
-                    case 0:
-                        return (value.getMeetings() - value2.getMeetings()) * -1;
-                    case 1:
-                        return (value.getAttendees() - value2.getAttendees()) * -1;
-                    case 2:
-                        return (value.getPlusMembers() - value2.getPlusMembers()) * -1;
-                }
-                return 0;
+                return entry.getValue().compareTo(mode, entry2.getValue());
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: compareTo is a function in `PulseEntry`. And it was exact duplicate of this.

**Comment by PareshMayani** [comment]
:+1: awesome contribution @tasomaniac

**Comment by tasomaniac** [comment]
@PareshMayani you already reviewed this right?
Any one up for merge @friedger @Splaktar ?

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java [hunk 2]
```diff
@@ -182,16 +179,25 @@ public void onNothingSelected(final AdapterView<?> parent) {
             }
         });
 
+        refreshSpinner(selectedPulse);
+    }
+
+    private void refreshSpinner(String selectedPulse) {
+
+        mSpinner.setAdapter(mSpinnerAdapter);
```
Comment (stefanhoth) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java]: This line needed to be reset every time? Looks out of scope for this method.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java [hunk 3]
```diff
@@ -117,23 +123,16 @@ public void setPulse(final int mode, Pulse pulse) {
         mMode = mode;
         mPulse.clear();
         mPulse.addAll(pulse.entrySet());
-        mPosition = new int[mPulse.size()];
+        //Only initialize if the positions are not provided.
+        //They are provided in constructor and coming from savedInstanceState of the Fragment.
+        if (mPositions == null || mPositions.length != mPulse.size()) {
```
Comment (stefanhoth) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: Should this init be down here? It feels this could be done at the beginning of the method or better yet in constructor.

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: We don't know the size before. Network operation is done, Pulse object is filled and then this is called. That's where we know the size.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java (hunk 2 above)
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java]: You are right. Fixing now.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java (hunk 1 above)
Comment (stefanhoth) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: Could you just make `PulseEntry` implement `Comparable` and avoid this here altogether?

**Comment by stefanhoth** [comment]
I reviewed bits of the code but I don't understand enough to assess the change. If you could explain again what you persist, where and why it would help me understand. It'll be best to comment the lines where something is happening.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java [hunk 4]
```diff
@@ -164,15 +164,12 @@ private void initSpinner(String selectedPulse) {
...
-        mSpinner.setAdapter(mSpinnerAdapter);
         mSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
             @Override
             public void onItemSelected(final AdapterView<?> parent, final View view, final int position, final long id) {
                 String previous = mViewPagerAdapter.getSelectedPulseTarget();
-                mViewPagerAdapter.setSelectedPulseTarget(mSpinnerAdapter.getItem(position));
                 if (!previous.equals(mSpinnerAdapter.getItem(position))) {
-                    Timber.d("Switching chapter!");
-                    mViewPagerAdapter.notifyDataSetChanged();
+                    refreshSpinner(mSpinnerAdapter.getItem(position));
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseActivity.java]: ViewPager's notifyDataSetChanged is not working because it aggressively cache the Fragment state which shouldn't be cached because we are changing the list completely. Eg. first we show countries, then we show cities in a specific country.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java [hunk 5]
```diff
@@ -39,13 +40,18 @@
 
     private LayoutInflater mInflater;
     private ArrayList<Map.Entry<String, PulseEntry>> mPulse;
-    private int[] mPosition;
+    private int[] mPositions;
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: When I disabled the ViewPager's aggressive caching, it solved the numbering problem for changing countries/cities. But it didn't solve when orientation change occurs. When orientation change occur in a page, the list scroll position is kept but the computed Positions were not kept. We may solve the problem with changing the algorithm to compute positions but it requires more work. I've just added kept the positions computed.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java [hunk 6]
```diff
@@ -76,13 +77,21 @@ public void onAttach(final Activity activity) {
...
     public void onActivityCreated(Bundle savedInstanceState) {
         super.onActivityCreated(savedInstanceState);
 
         mTarget = getArguments().getString(ARG_TARGET);
         mMode = getArguments().getInt(ARG_MODE);
 
-        mAdapter = new PulseAdapter(getActivity());
+        int[] positions = savedInstanceState != null
+                ? savedInstanceState.getIntArray(INSTANCE_STATE_POSITIONS) : null;
+        mAdapter = new PulseAdapter(getActivity(), positions);
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java]: Here I am saving the calculated positions of the adapter.

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseFragment.java]: By meaning positions, I mean that rankings of the countries/cities. The ones related to the numbering problem in the screenshot in the original issue.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java (hunk 1 above)
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: Sure. Makes sense.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java (hunk 5 above)
Comment (stefanhoth) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: Renaming this private field changes the caching behavior?

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: No :) While I was doing it I also refactored it. mPosition is not suitable because it was not plural. We are holding multiple items in it.

File: app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java (hunk 1 above)
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: The type of the objects is `Map.Entry<String, PulseEntry>` not just `PulseEntry`. Map.Entry does not implement Comparable. So it will not work. Getting rid of `Map.Entry<String, PulseEntry>` is out of this PR's scope I think.

Comment (stefanhoth) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: This adapter manages an `ArrayList` of `Map.Entry`. WAT? :wink:

I'll try to address this later because it bothers me physically. :+1:

Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: I said OMG when I first saw it. :) It is everywhere in the adapter. The key in the map entry is actually used as the title.

Comment (stefanhoth) [inline app/src/main/java/org/gdg/frisbee/android/pulse/PulseAdapter.java]: Tracked as #487

**Comment by stefanhoth** [comment]
Ok, let's :ship: it.
