### PR TITLE
selected chapter fix

### LINKED ISSUE #286: Selected Chapter in Main changes unexpectedly
Home chapter changes with the following steps:
Go to Google Developer Experts
Select multiple tabs (ex. browse through Adwords, GAPI, UX, Chrome, Angular, etc)
Go back to Home GDG - switches to GDG Gafsa

### PR DESCRIPTION
**Pull request by tasomaniac**
We were using EXTRA_CHAPTER_ID to send Parcelable Chapter somewhere and String Chapter Id elsewhere.
It is now EXTRA_CHAPTER and it always uses Chapter object.

Should also fix #286 but 100% sure

### CODE REVIEW

File: app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java [hunk 1]
```diff
@@ -90,7 +87,7 @@ private void sendEventNotification(Bundle extras) {
                 .forPattern("YYYY-MM-dd'T'HH:mm:ss.SSS'Z'");
 
         DateTime start = df.parseDateTime(extras.getString("start"));
-        DateTime end = df.parseDateTime(extras.getString("end"));
+//        DateTime end = df.parseDateTime(extras.getString("end"));
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java]: was not used and IDE was giving warning.

File: app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java [hunk 2]
```diff
@@ -120,8 +118,8 @@ public void onErrorResponse(VolleyError volleyError) {
             @Override
             public void onGet(Object item) {
                 Directory directory = (Directory) item;
-                mLoadSwitcher.setDisplayedChild(1);
                 addChapters(directory.getGroups());
+                mLoadSwitcher.setDisplayedChild(1);
```
Comment (tasomaniac) [inline app/src/main/java/org/gdg/frisbee/android/fragment/FirstStartStep1Fragment.java]: Just to be consistent with the lines below.

File: app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java (hunk 1 above)
Comment (friedger) [inline app/src/main/java/org/gdg/frisbee/android/service/GcmIntentService.java]: Could be deleted..
